package com.qaprosoft.zafira

class JobParameters {

    public static final String PROJECT = project = "project"
    public static final String SUB_PROJECT = project = "sub_project"
    public static final String EMAIL_LIST = project = "email_list"
    public static final String FAILURE_EMAIL_LIST = project = "failure_email_list"
    public static final String ZAFIRA_SERVICE_URL = project = "ZAFIRA_SERVICE_URL"
    public static final String ZAFIRA_ACCESS_TOKEN = project = "ZAFIRA_ACCESS_TOKEN"
    public static final String JOB_MAX_RUN_TIME = project = "JOB_MAX_RUN_TIME"
    public static final String DEVELOP = project = "develop"
    public static final String BUILD_NUMBER = project = "BUILD_NUMBER"
    public static final String CARINA_CORE_VERSION = project = "CARINA_CORE_VERSION"
    public static final String SUITE = project = "suite"
    public static final String BRANCH = project = "branch"
    public static final String ENV = project = "env"
    public static final String DEVICE = project = "device"
    public static final String BROWSER = project = "browser"
    public static final String BROWSER_VERSION = project = "browser_version"
    public static final String DEFAULT_POOL = project = "DefaultPool"
    public static final String PLATFORM = project = "platform"
    public static final String CORE_LOG_LEVEL = project = "CORE_LOG_LEVEL"
    public static final String SELENIUM_URL = project = "SELENIUM_URL"
    public static final String ZAFIRA_BASE_CONFIG = project = "ZAFIRA_BASE_CONFIG"
    public static final String JOB_URL = project = "JOB_URL"
    public static final String CI_PARENT_URL = project = "ci_parent_url"
    public static final String CI_PARENT_BUILD = project = "ci_parent_build"
    public static final String ENABLE_VNC = project = "enableVNC"
    public static final String ENABLE_VIDEO = project = "enableVideo"
    public static final String JACOCO_ENABLE = project = "JACOCO_ENABLE"
    public static final String DEBUG = project = "debug"
    public static final String OVERRIDE_FIELDS = project = "overrideFields"
    public static final String NODE = project = "node"
    public static final String CI_RUN_ID = project = "ci_run_id"
    public static final String JOB_NAME = project = "JOB_NAME"
    public static final String JACOCO_BUCKET = project = "JACOCO_BUCKET"

}